name: projetotriade
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Pacote de ícones iOS (já veio)
  cupertino_icons: ^1.0.8

  # Gerenciamento de estado (vamos usar Provider)
  provider: ^6.0.5

  # Pacote para requisições HTTP (para chamar o backend)
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # <-- ALTERE DE ^5.0.0 PARA ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/




